export const MAIN_SET_USER = 'MAIN_SET_USER'
export const MAIN_FETCH_USER = 'MAIN_FETCH_USER'

export const MAIN_MAKE_MENU = 'MAIN_MAKE_MENU'

export const MAIN_ADD_OPEN_PAGE = 'MAIN_ADD_OPEN_PAGE'

export const MAIN_TOGGLE_MENU = 'MAIN_TOGGLE_MENU'

export const MAIN_MAKE_TAG_LIST = 'MAIN_MAKE_TAG_LIST'

export const MAIN_TAGS_CLOSE_ALL = 'MAIN_TAGS_CLOSE_ALL'

export const MAIN_TAGS_CLOSE_ETC = 'MAIN_TAGS_CLOSE_ETC'
